FROM golang:1.22-alpine

WORKDIR /usr/src/app

# Copy dependency manifests
COPY ./services/checkout/go.mod ./services/checkout/go.sum ./
RUN go mod download

# Copy application source code and shared pb directory
COPY ./services/checkout/ ./
COPY ./pb/ ./pb/

# Build the binary directly inside the runtime space
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o checkout ./

ENV CHECKOUT_PORT=5050
EXPOSE 5050

ENTRYPOINT ["./checkout"]

