FROM node:20

WORKDIR /usr/src/app

COPY ./services/payment/package*.json ./
RUN npm install --only=production

COPY ./services/payment/ ./

# Copy the shared proto file
COPY ./pb/demo.proto ./demo.proto

ENV PAYMENT_PORT=50051
EXPOSE 50051

CMD ["node", "index.js"]
